#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mo-data-pv
#  labels:
#    type: local
#spec:
#  storageClassName: generic
#  capacity:
#    storage: 500Mi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/var/lib/mongo"
#---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pv
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi

  